# https://github.com/gohugoio/hugoThemes#themetoml

name = "Paper"
license = "MIT"
licenselink = "https://github.com/raphi011/hugo-dev/blob/main/LICENSE"
description = "A clean, minimal Hugo theme"
homepage = "https://github.com/raphi011/hugo-dev"
tags = ["blog", "minimal", "clean", "responsive", "dark mode"]
features = ["blog", "responsive", "dark mode", "syntax highlighting"]
min_version = "0.145.0"

[author]
  name = "raphi011"
  homepage = "https://github.com/raphi011"
