baseURL = "https://example.org/"
languageCode = "en-us"
title = "Paper"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

# Theme is resolved via Hugo Modules
[module]
  [[module.imports]]
    path = "github.com/raphi011/hugo-dev"

[menus]
  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 10

[params]
  description = "A clean, minimal Hugo theme for developers"
  author = "Raphael Gruber"
  commitHash = ""

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/raphi011"
    icon = "github.svg"
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/raphael-gruber-944300137"
    icon = "linkedin.svg"
  [[params.social]]
    name = "RSS"
    url = "/index.xml"
    icon = "rss.svg"

[markup]
  [markup.highlight]
    codeFences = false
